#!/usr/bin/env node
import { randomBytes } from "crypto";
import { copyFileSync, existsSync, readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const examplePath = join(root, ".env.example");
const localPath = join(root, ".env.local");

if (!existsSync(examplePath)) {
  console.error("Missing .env.example");
  process.exit(1);
}

let content = readFileSync(examplePath, "utf8");

function setIfEmpty(key, value) {
  const re = new RegExp(`^${key}=.*$`, "m");
  if (re.test(content)) {
    const line = content.match(re)?.[0] ?? "";
    if (line === `${key}=` || line.endsWith('=""')) {
      content = content.replace(re, `${key}=${value}`);
    }
  } else {
    content += `\n${key}=${value}`;
  }
}

setIfEmpty("NEXT_PUBLIC_SITE_URL", "http://localhost:3000");
setIfEmpty("STRIPE_WEBHOOK_SECRET", randomBytes(24).toString("hex"));
setIfEmpty("CRON_SECRET", randomBytes(24).toString("hex"));

const header = `# Generated by scripts/setup-env.mjs\n\n`;
if (!content.startsWith("# Generated")) {
  content = header + content;
}

writeFileSync(localPath, content, "utf8");
console.log("Wrote .env.local");
console.log("Next: npm run db:setup (local Docker) or npm run db:setup:cloud with SUPABASE_ACCESS_TOKEN");
